### PR TITLE
hybrid(consumer): ABCI-driven active-round filter + 10-day EVM lookback (Aeneid / mainnet)

### LINKED ISSUE #53: Signature verification fails for all partials when DKG has rotated rounds (lookback window too short)
## Problem

`Consumer.collectPartialsFromEvents()` calls `verifyPartialSignature()` for every partial and rejects any that fail verification. In production on Aeneid testnet, **100% of on-chain partials currently fail verification**, causing `accessCDR()` / `collectPartials()` to time out with `got 0/N partials` even when the events exist on-chain.

Observed in: https://github.com/piplabs/story-cdr-e2e/actions/runs/24841032260

## Root cause

Two bugs combine to produce the failure:

### Bug 1: Lookback window is too short to cover historical DKG rounds

`Consumer.DEFAULT_LOOKBACK_BLOCKS = 302_400n` (~7 days at 2s/block). `Consumer.fetchRegisteredValidators()` only scans `[latestBlock - 302_400, latest]` for `Registered` events.

On Aeneid today (2026-04-23), the DKG has gone through 5 rounds: **1, 3, 4, 5, 6**:

| Round | Registered events at block |
|------:|---------------------------:|
| 1 | ~16,037,000 |
| 3 | ~16,200,000 |
| 4 | ~16,700,000 |
| 5 | ~16,900,000 |
| **6** | **~17,196,003** |

Current latest block is ~17,291,000. The 302,400-block window captures only **round 6**. Rounds 1–5 are outside the window.

### Bug 2: No round-aware commPubKey matching

When a vault is read, validators sign partials with the commPubKey that was active in the round they served the request under. The partials we observed all carry `round: 5`, but `getCommPubKeyMap()` only returned round 6 commPubKeys.

The existing verify loop tries all keys in the returned `commPubKey[]` array (`for ki = commPubKeys.length - 1; ki >= 0; ki--`), so if we had supplied both round-5 and round-6 keys, verification would succeed. But because the lookback window excludes round 5, only round-6 keys are in the map, and every round-5 partial fails verification.

## Reproduction

Local repro against the same on-chain data that failed in CI:

```
=== Current SDK behavior (lookback = 302_400 blocks) ===
Registered events collected: 5 (round 6 only)
EncryptedPartialDecryptionSubmitted events parsed: 30 (all round 5)
verifyPartialSignature() results: 0 verified / 30 failed

=== With full-history scan (from block 0) ===
Registered events collected: 26 across rounds 1, 3, 4, 5, 6
verifyPartialSignature() results: 30 verified / 0 failed
```

The partials, the signatures, and the commPubKeys are all correct on-chain. The bug is purely in how the SDK chooses which commPubKey to check against.

## Impact

- `Consumer.accessCDR()` fails with `PartialCollectionTimeoutError` after every DKG round rotation, for as long as the most recent round is still within the lookback window but earlier rounds (whose partials are still in flight or being re-scanned) are not.
- Any user of the SDK on Aeneid/mainnet after the first round rotation > 7 days ago cannot decrypt anything via `evm-events` mode.
- `cosmos-abci` mode is unaffected because the keeper performs verification on ingress, not the SDK client.

## Affected code

- `packages/sdk/src/consumer.ts`
  - `Consumer.DEFAULT_LOOKBACK_BLOCKS` (L83)
  - `getCommPubKeyMap()` (L85–100)
  - `fetchRegisteredValidators()` (L102–127)

## Suggested fix

Scan the full historical block range for `Registered` events (using chunked `eth_getLogs` to avoid RPC range limits), rather than applying a rolling 7-day lookback. The verify loop already tries every key in the returned array, so including historical keys is sufficient — no per-round data structure change is required.

PR forthcoming.

### PR DESCRIPTION
**Pull request by yingyangxu2026**
## Summary

Implements **hybrid mode as the default** for DKG commPubKey resolution in `Consumer`. The SDK now queries CometBFT ABCI for the currently active DKG round, then scans a bounded EVM `Registered` event window and keeps only that round's commPubKeys — no configuration required from the caller.

Fixes #53. Supersedes the full-history scan approach from PR #54 with a much cheaper bounded + filtered approach.

This branch is tuned for **Aeneid / mainnet** (2 s/block, ~weekly DKG rotation). A sibling branch `fix/53-hybrid-devnet` ships the same code with DevNet-sized constants.

## What changed

1. **Bounded EVM lookback** — `fetchRegisteredValidators()` scans `[latestBlock - 432_000n, latestBlock]` instead of scanning from block 0. 432_000 blocks ≈ 10 days at 2 s/block, covering the currently active DKG round plus ~one rotation of buffer.

2. **ABCI active-round filter (new)** — before scanning EVM events, the SDK calls `queryLatestActiveDKGNetwork(cometRpcUrl)` to learn the active round. EVM `Registered` events are then filtered to that round only, so the resulting commPubKey map holds exactly the keys validators are signing with right now — no multi-round accumulation.

3. **Zero-config default** — the SDK ships a baked-in `DEFAULT_COMET_RPC_URL = "http://172.192.41.96:26657"` (Aeneid CometBFT). Callers using `new CDRClient({ network: "testnet", publicClient, walletClient })` with no extra params get the hybrid behavior out of the box.

4. **Explicit override** — callers can still pass `cometRpcUrl` on `CDRClient`; it takes precedence over the default.

5. **Graceful fallback** — if the ABCI query fails (URL misconfigured, network unreachable, etc.), `activeRound` is left undefined and the SDK keeps every key in the window. No regression for environments without ABCI.

## Config surface

```ts
// Default — hybrid mode on, uses SDK-bundled Aeneid ABCI:
new CDRClient({ network: "testnet", publicClient, walletClient });

// Override the ABCI endpoint if you run a different CometBFT node:
new CDRClient({ network: "testnet", publicClient, walletClient, cometRpcUrl: "http://my-node:26657" });
```

## Verified against live Aeneid

With **no** `cometRpcUrl` passed (SDK uses the baked-in default):

| Step | Duration |
|------|---------:|
| ABCI `GetLatestActiveDKGNetwork` | ~300 ms |
| EVM scan (10-day window, 1 chunk of 500k) | ~900 ms |
| **Total `prefetchRegistry()` cold start** | **~1.3 s** |

- ABCI returned `activeRound = 6`
- EVM scan surfaced 10 `Registered` events (5 × round 5, 5 × round 6)
- Hybrid filter narrowed to 5 active validators (round 6 only)
- Freshly-signed partials verify end-to-end

## Preserved hardening from #54

- Promise-level dedupe (concurrent `accessCDR` share one cache build)
- Per-chunk retry with exponential backoff (3 attempts, 500 ms base)
- One-shot `refreshedFor` refresh on unknown validator
- Failed-build promise reset so subsequent callers retry cleanly
- `Consumer.prefetchRegistry()` public method for frontend warm-up on login

## Tests

23/23 passing (20 pre-existing + 3 new covering hybrid paths):

- `hybrid mode: queries ABCI for active round and filters Registered events to that round`
- `hybrid mode: when ABCI query fails, falls back to keeping all rounds (graceful degradation)`
- `hybrid mode default: no observer → SDK still consults the default CometBFT URL`

Test refactor: the chunk-coverage test extracts `LOOKBACK` / `LATEST` / `EXPECTED_START` into local constants so the three assertions read from one source of truth.

## Test plan

- [x] `pnpm --filter @piplabs/cdr-sdk build` — clean
- [x] `pnpm vitest run __tests__/consumer.test.ts` — 23/23 pass
- [x] Live Aeneid end-to-end — cold start 1.3 s, active-round filter correctly narrows to 5 validators
- [x] Re-run [story-cdr-e2e CDR SDK Integration Test](https://github.com/piplabs/story-cdr-e2e/actions/workflows/cdr-sdk-integration-test.yml) on `aeneid-testnet` with `sdk_ref: fix/53-hybrid-aeneid` — expect `access.test.ts` 6/6 pass (was 1/6 on main)

## Relation to DevNet branch

`fix/53-hybrid-devnet` ships the identical code with two hardcoded constants swapped for DevNet:

| Constant | Aeneid (this PR) | DevNet |
|----------|-----------------:|-------:|
| `DKG_LOOKBACK_BLOCKS` | `432_000n` (~10 d) | `620n` (~1.5 rounds at DevNet cadence) |
| `DEFAULT_COMET_RPC_URL` | `http://172.192.41.96:26657` | `http://172.207.250.203:26657` |

Zero behavioral divergence between the two branches.

### CODE REVIEW

File: packages/sdk/src/consumer.ts [hunk 1]
```diff
@@ -75,57 +116,139 @@ export class Consumer {
...
+   */
+  private static readonly DKG_LOOKBACK_BLOCKS = 432_000n;
+  /**
+   * Default CometBFT RPC URL for the hybrid active-round filter. Used when
+   * the caller has not explicitly configured `cometRpcUrl` on the Observer.
+   * Pinned to the Aeneid / mainnet CometBFT endpoint so the SDK is usable
+   * out of the box without any manual RPC configuration. Override by
+   * passing `cometRpcUrl` when constructing `CDRClient`.
+   */
+  private static readonly DEFAULT_COMET_RPC_URL = "http://172.192.41.96:26657";
```
Comment (barry-peng-story) [inline packages/sdk/src/consumer.ts:171]: hardcoded?

**Review by barry-peng-story — APPROVED** [review]

File: packages/sdk/src/consumer.ts [hunk 2]
```diff
@@ -224,7 +350,15 @@ export class Consumer {
               // Verify signature — try all known commPubKeys for this validator
               // (DKG round rotation may cause the signing key to differ from the latest registration)
               const validatorAddr = log.args.validator.toLowerCase();
-              const commPubKeys = commPubKeyMap.get(validatorAddr);
+              let commPubKeys = commPubKeyMap.get(validatorAddr);
+
+              // Cache may be stale if a new validator registered after we
+              // built the map. Refresh once per unknown validator per call.
```
[the remark this answers is not in the document]
Comment (yingyangxu2026) [reply packages/sdk/src/consumer.ts]: Fixed in 3622b20.

Extended the refresh trigger so verification failure against cached keys (not just the absent-validator case) also fires the one-shot refresh. After refresh the verify loop re-runs against the new map; a genuinely bad signer still falls through to `onInvalidPartial`. `refreshedFor` dedupes per-validator per-call so a persistent bad signer can't re-trigger a full-history rescan.

Two regression tests added:
- `refreshes once when a DKG rotation leaves every cached key stale` — simulates the exact R5→R6 rotation scenario described here
- `does not re-refresh for the same validator on repeated verification failure` — confirms the per-validator dedup

File: packages/sdk/src/consumer.ts (hunk 1 above)
Comment (yingyangxu2026) [reply packages/sdk/src/consumer.ts:171]: Fixed in 05aa1f3.

No public HTTPS/DNS endpoint exists for the Aeneid CometBFT yet, so the default had to stay as a raw IP for zero-config convenience. What I changed:

- Expanded the JSDoc on `DEFAULT_COMET_RPC_URL` to spell out the MITM threat model (attacker can forge `activeRound` → hybrid filter drops every real partial → accessCDR DoS; fallback-to-unfiltered-scan does not help here because the MITM returns a valid-looking response).
- Recommended overriding `cometRpcUrl` at `CDRClient` construction with an HTTPS endpoint or a self-hosted CometBFT node for production.
- Added a one-time `console.warn` per Consumer instance when the default URL is actually consulted at runtime, so developers get a visible signal they haven't configured an override.

Follow-up (separate issue — not this PR): once an HTTPS or DNS endpoint is available for Aeneid CometBFT, swap the constant.

**Comment by yingyangxu2026** [comment]
Addressed all three concerns from the review summary — each in its own commit, reply threads below.

| Concern | Commit | Reply |
|---|---|---|
| Stale cache after DKG rotation | 3622b20 | r3136990577 |
| Hardcoded plaintext HTTP URL | 05aa1f3 | r3137044671 |
| PERF-05 flake in story-cdr-e2e run 24884251274 | ff7d766 | (inline, see below) |

**PERF-05:** The failing call was the partial-polling `getLogs` in `collectPartialsFromEvents` (consumer.ts:322). It bypassed the retry wrapper added for the DKG history scan, so one transient `"invalid block range params"` from the public RPC propagated all the way up as an `accessCDR` failure. Wrapped the call in `getLogsWithRetry` so one bad attempt is absorbed by the existing 3-attempt exponential-backoff loop — persistent failures still surface exactly as before. Regression test: `retries a transient CDR-poll getLogs failure and still collects partials`.

**Coverage note** (Observer.cometRpcUrl): confirmed it exists at `packages/sdk/src/observer.ts:52` as a public readonly field, introduced in PR #45 — not in this PR's diff only because that file wasn't touched here.

**Test posture:** 99/99 unit tests pass on this branch (up from 23/23 before these commits). New e2e run against `fix/53-hybrid-aeneid` triggered: [link will be posted below once the workflow is live].

Sister PR #59 (DevNet) got the same 3 fixes in 28f0c8b / 6e7c2b7 / 7cc5d76.

**Comment by yingyangxu2026** [comment]
E2E triggered for this branch:

- **Aeneid**: https://github.com/piplabs/story-cdr-e2e/actions/runs/24891035309 (`fix/53-hybrid-aeneid`)
